version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/utils:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: client
    build: ./client
    env_file:
      - ./client/.env.docker
    ports:
      - "3000:3000"
      environment:
      REACT_APP_PROXY: http://backend:5000
      depends_on:
      - backend



volumes:
  data:
