version: "3.8"
services:
  mongodb:
    container_name: mongop
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_PROXY: http://backend:5000
    depends_on:
       - backend


  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379
    depends_on:
      - mongodb

volumes:
  data:
