version: "3.8"
services:
  mongodbp:
    container_name: mongop
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backendp
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongodbp

  frontend:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_PROXY: http://backend:5000
    depends_on:
       - backend

volumes:
  data:
